////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 14.7
//  \   \         Application : xaw2verilog
//  /   /         Filename : clkwiz.v
// /___/   /\     Timestamp : 07/18/2023 18:29:11
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: xaw2verilog -intstyle /home/ise/git/firmware-surf/par/ipcore_dir/clkwiz.xaw -st clkwiz.v
//Design Name: clkwiz
//Device: xc3s2000-4fg456
//
// Module clkwiz
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
`timescale 1ns / 1ps

module clkwiz(CLKIN_IN, 
              PSCLK_IN, 
              PSEN_IN, 
              PSINCDEC_IN, 
              RST_IN, 
              CLK0_OUT, 
              CLK2X_OUT, 
              CLK2X180_OUT, 
              LOCKED_OUT, 
              PSDONE_OUT, 
              STATUS_OUT);

    input CLKIN_IN;
    input PSCLK_IN;
    input PSEN_IN;
    input PSINCDEC_IN;
    input RST_IN;
   output CLK0_OUT;
   output CLK2X_OUT;
   output CLK2X180_OUT;
   output LOCKED_OUT;
   output PSDONE_OUT;
   output [7:0] STATUS_OUT;
   
   wire CLKFB_IN;
   wire CLK0_BUF;
   wire CLK2X_BUF;
   wire CLK2X180_BUF;
   wire GND_BIT;
   
   assign GND_BIT = 0;
   assign CLK0_OUT = CLKFB_IN;
   BUFG  CLK0_BUFG_INST (.I(CLK0_BUF), 
                        .O(CLKFB_IN));
   BUFG  CLK2X_BUFG_INST (.I(CLK2X_BUF), 
                         .O(CLK2X_OUT));
   BUFG  CLK2X180_BUFG_INST (.I(CLK2X180_BUF), 
                            .O(CLK2X180_OUT));
   DCM #( .CLK_FEEDBACK("1X"), .CLKDV_DIVIDE(2.0), .CLKFX_DIVIDE(1), 
         .CLKFX_MULTIPLY(4), .CLKIN_DIVIDE_BY_2("FALSE"), .CLKIN_PERIOD(8.000), 
         .CLKOUT_PHASE_SHIFT("VARIABLE"), .DESKEW_ADJUST("SYSTEM_SYNCHRONOUS"), 
         .DFS_FREQUENCY_MODE("LOW"), .DLL_FREQUENCY_MODE("LOW"), 
         .DUTY_CYCLE_CORRECTION("TRUE"), .FACTORY_JF(16'h8080), 
         .PHASE_SHIFT(0), .STARTUP_WAIT("FALSE") ) DCM_INST (.CLKFB(CLKFB_IN), 
                 .CLKIN(CLKIN_IN), 
                 .DSSEN(GND_BIT), 
                 .PSCLK(PSCLK_IN), 
                 .PSEN(PSEN_IN), 
                 .PSINCDEC(PSINCDEC_IN), 
                 .RST(RST_IN), 
                 .CLKDV(), 
                 .CLKFX(), 
                 .CLKFX180(), 
                 .CLK0(CLK0_BUF), 
                 .CLK2X(CLK2X_BUF), 
                 .CLK2X180(CLK2X180_BUF), 
                 .CLK90(), 
                 .CLK180(), 
                 .CLK270(), 
                 .LOCKED(LOCKED_OUT), 
                 .PSDONE(PSDONE_OUT), 
                 .STATUS(STATUS_OUT[7:0]));
endmodule
